---
config:
  look: classic
  theme: base
  layout: fixed
---
flowchart TD
 subgraph trainable[" "]
    direction LR
        dec1[/"Custom LR-HR Decoder"\]
        note1["Cross Attention"]
        custom_enc2[\"Custom HR-LR Encoder"/]
  end
 subgraph pretrained[" "]
    direction LR
        lr_hr_enc[\"LR-HR Encoder"/]
        main_llm["Main LLM Layers"]
        dec2[/"HR-LR Decoder"\]
        note2["Cross Attention"]
  end
    input_lr["Input Low-Resource"] --> lr_hr_emb["LR-HR Embeddings"]
    input_hr["Input High-Resource"] --> llm_emb["LLM Embeddings"]
    lr_hr_emb --> lr_hr_enc
    llm_emb --> note1
    lr_hr_enc --> note1
    note1 --> dec1
    dec1 --> main_llm
    main_llm <--> custom_enc2
    target_lr["Target Low-Resource"] --> hr_lr_emb["HR-LR Embeddings"]
    custom_enc2 --> note2
    hr_lr_emb --> note2
    note2 --> dec2
    dec2 --> output["Output Logits"]
    title2["**Pre-trained Components**"] ~~~ pretrained
    n1["**Trainable Components**"] ~~~ trainable
    n1@{ shape: text}
     dec1:::trainableComp
     dec1:::Peach
     note1:::noBorder
     note1:::noBorder
     custom_enc2:::trainableComp
     custom_enc2:::Peach
     lr_hr_enc:::pretrainedComp
     main_llm:::pretrainedComp
     dec2:::pretrainedComp
     note2:::noBorder
     note2:::noBorder
     input_lr:::input
     lr_hr_emb:::embedding
     input_hr:::input
     llm_emb:::embedding
     target_lr:::input
     hr_lr_emb:::embedding
     output:::output
     title2:::groupTitle
     n1:::groupTitle
    classDef input fill:#f0f4f8,stroke:#64b5f6,stroke-width:1px,color:#1976d2
    classDef embedding fill:#ffffff,stroke:#b39ddb,stroke-width:1px,color:#5e35b1,stroke-dasharray:3 3
    classDef trainableComp fill:#81d4fa,stroke:#29b6f6,stroke-width:1px,color:#0277bd
    classDef pretrainedComp fill:#80cbc4,stroke:#26a69a,stroke-width:1px,color:#00695c
    classDef output fill:#fafafa,stroke:#90a4ae,stroke-width:1px,color:#455a64
    classDef noBorder fill:none,stroke:none,color:#546e7a
    classDef Peach stroke-width:1px, stroke-dasharray:none, stroke:#FBB35A, fill:#FFEFDB, color:#8F632D
    classDef groupTitle fill:none, stroke:none, color:#000000, font-size:20px
    style pretrained fill:#e0f2f1,stroke:#e0e0e0,stroke-width:1px,color:#424242
    style trainable fill:#e1f5fe,stroke:#e0e0e0,stroke-width:1px,color:#424242
